apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mutating-webhook
  namespace: flux-system
spec:
  secretRef:
    name: gh-auth
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com:kazimmehdi/mutating-webhook.git
