apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mutating-webhook
  namespace: flux-system
spec:
  releaseName: mutating-webhook
  interval: 5m
  targetNamespace: mutating-webhook
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: mutating-webhook
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    webhook:
      enabled: true
      failurePolicy: Fail
      servicePort: 443
